name: Test
permissions:
    contents: read
on: [push, pull_request, workflow_call]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4

            - name: Install Dependencies
              run: pnpm i --frozen-lockfile --ignore-scripts

            - name: Install Playwright Browsers
              run: pnpm exec playwright install --with-deps chromium

            - name: Run Tests # builds internally - see the "test" script
              run: pnpm test
